from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Float
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from database.connection import Base


# =========================================================
# USER
# =========================================================

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    email = Column(String(150), unique=True, nullable=False, index=True)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    resumes = relationship(
        "Resume",
        back_populates="user",
        cascade="all, delete-orphan"
    )

    career_profile = relationship(
        "CareerProfile",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan"
    )

    # Interview sessions
    interview_sessions = relationship(
        "InterviewSession",
        back_populates="user",
        cascade="all, delete-orphan"
    )


# =========================================================
# RESUME
# =========================================================

class Resume(Base):
    __tablename__ = "resumes"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    filename = Column(String(255), nullable=False)
    file_path = Column(String(500), nullable=False)
    extracted_text = Column(Text, nullable=True)

    # AI analysis generated by Gemini
    ai_analysis = Column(Text, nullable=True)

    uploaded_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="resumes")


# =========================================================
# CAREER PROFILE
# =========================================================

class CareerProfile(Base):
    __tablename__ = "career_profiles"

    id = Column(Integer, primary_key=True, index=True)

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        unique=True,
        nullable=False
    )

    target_role = Column(String(150), nullable=True)
    experience_level = Column(String(50), nullable=True)
    skills = Column(Text, nullable=True)
    education = Column(Text, nullable=True)
    projects = Column(Text, nullable=True)

    user = relationship("User", back_populates="career_profile")


# =========================================================
# INTERVIEW SESSION
# =========================================================

class InterviewSession(Base):
    __tablename__ = "interview_sessions"

    id = Column(Integer, primary_key=True, index=True)

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False
    )

    job_description = Column(Text, nullable=False)

    # Overall final interview score
    overall_score = Column(Float, nullable=True)

    # Final recommendation
    hiring_recommendation = Column(
        String(100),
        nullable=True
    )

    # Final AI-generated report
    final_report = Column(Text, nullable=True)

    status = Column(
        String(50),
        default="in_progress"
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )

    completed_at = Column(
        DateTime(timezone=True),
        nullable=True
    )

    user = relationship(
        "User",
        back_populates="interview_sessions"
    )

    questions = relationship(
        "InterviewQuestion",
        back_populates="session",
        cascade="all, delete-orphan"
    )


# =========================================================
# INTERVIEW QUESTION
# =========================================================

class InterviewQuestion(Base):
    __tablename__ = "interview_questions"

    id = Column(Integer, primary_key=True, index=True)

    session_id = Column(
        Integer,
        ForeignKey("interview_sessions.id"),
        nullable=False
    )

    question_number = Column(
        Integer,
        nullable=False
    )

    question = Column(
        Text,
        nullable=False
    )

    category = Column(
        String(100),
        nullable=True
    )

    difficulty = Column(
        String(50),
        nullable=True
    )

    # Candidate's answer
    answer = Column(
        Text,
        nullable=True
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )

    session = relationship(
        "InterviewSession",
        back_populates="questions"
    )

    evaluation = relationship(
        "InterviewEvaluation",
        back_populates="question",
        uselist=False,
        cascade="all, delete-orphan"
    )


# =========================================================
# INTERVIEW EVALUATION
# =========================================================

class InterviewEvaluation(Base):
    __tablename__ = "interview_evaluations"

    id = Column(Integer, primary_key=True, index=True)

    question_id = Column(
        Integer,
        ForeignKey("interview_questions.id"),
        nullable=False,
        unique=True
    )

    technical_correctness = Column(
        Float,
        nullable=True
    )

    relevance = Column(
        Float,
        nullable=True
    )

    clarity = Column(
        Float,
        nullable=True
    )

    communication = Column(
        Float,
        nullable=True
    )

    overall_score = Column(
        Float,
        nullable=True
    )

    strengths = Column(
        Text,
        nullable=True
    )

    weaknesses = Column(
        Text,
        nullable=True
    )

    improvements = Column(
        Text,
        nullable=True
    )

    feedback = Column(
        Text,
        nullable=True
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )

    question = relationship(
        "InterviewQuestion",
        back_populates="evaluation"
    )